"""undo test

Revision ID: 200fd09ac530
Revises: 350661252922
Create Date: 2023-01-13 15:58:02.215956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '200fd09ac530'
down_revision = '350661252922'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
