"""undo test

Revision ID: 350661252922
Revises: f06d1105bb68
Create Date: 2023-01-13 15:56:59.952716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350661252922'
down_revision = 'f06d1105bb68'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'test_col')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('test_col', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
