"""add team_id to players.json

Revision ID: 5da9228e157d
Revises: 6c665dde0ce1
Create Date: 2023-11-24 16:13:22.219329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5da9228e157d'
down_revision = '6c665dde0ce1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
