"""add team_id to player table

Revision ID: 6c665dde0ce1
Revises: 200fd09ac530
Create Date: 2023-11-24 16:04:32.894503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c665dde0ce1'
down_revision = '200fd09ac530'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('players', sa.Column('team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'players', 'teams', ['team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'players', type_='foreignkey')
    op.drop_column('players', 'team_id')
    # ### end Alembic commands ###
