"""test

Revision ID: f06d1105bb68
Revises: 69e6a9210480
Create Date: 2023-01-13 15:55:07.979785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f06d1105bb68'
down_revision = '69e6a9210480'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('test_col', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'test_col')
    # ### end Alembic commands ###
